/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package com.tns.components.notifications;

import com.tns.RuntimeHelper;
import com.tns.Runtime;

@com.tns.JavaScriptImplementation(javaScriptFile = "./vendor.js")
public class MyJobService extends android.app.job.JobService
    implements com.tns.NativeScriptHashCodeProvider {
  public MyJobService() {
    super();
  }

  public boolean onStartJob(android.app.job.JobParameters param_0) {
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    return (boolean) com.tns.Runtime.callJSMethod(this, "onStartJob", boolean.class, args);
  }

  public boolean onStopJob(android.app.job.JobParameters param_0) {
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    return (boolean) com.tns.Runtime.callJSMethod(this, "onStopJob", boolean.class, args);
  }

  public void onCreate() {
    super.onCreate();
    if (!com.tns.Runtime.isInitialized()) {
      com.tns.Runtime runtime = com.tns.RuntimeHelper.initRuntime(this);
      runtime.run();
    }
    com.tns.Runtime.initInstance(this);
  }

  public int hashCode__super() {
    return super.hashCode();
  }

  public boolean equals__super(java.lang.Object other) {
    return super.equals(other);
  }
}
