/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package com.tns.notifications;

import com.tns.RuntimeHelper;
import com.tns.Runtime;

@com.tns.JavaScriptImplementation(javaScriptFile = "./bundle.js")
public class NotificationIntentService extends android.app.IntentService
    implements com.tns.NativeScriptHashCodeProvider {
  public NotificationIntentService(java.lang.String param_0) {
    super(param_0);
  }

  protected void onHandleIntent(android.content.Intent param_0) {
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    com.tns.Runtime.callJSMethod(this, "onHandleIntent", void.class, args);
  }

  public void onCreate() {
    super.onCreate();
    if (!com.tns.Runtime.isInitialized()) {
      com.tns.Runtime runtime = com.tns.RuntimeHelper.initRuntime(this);
      runtime.run();
    }
    com.tns.Runtime.initInstance(this);
  }

  public int hashCode__super() {
    return super.hashCode();
  }

  public boolean equals__super(java.lang.Object other) {
    return super.equals(other);
  }
}
